steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(python.version)
    architecture: '$(python.architecture)'
    addToPath: true
  displayName: Use Python $(python.version)

- template: install-dependencies.yml

- script: |
    echo '##vso[task.setvariable variable=PIPENV_DEFAULT_PYTHON_VERSION]$(python.version)'
  env:
    PYTHON_VERSION: $(python.version)

- template: create-virtualenv.yml
  parameters:
    python_version: $(python.version)

- ${{ if eq(parameters.vmImage, 'windows-2019') }}:
  - template: run-tests-windows.yml
    parameters:
      python_version: $(python.version)
- ${{ if ne(parameters.vmImage, 'windows-2019') }}:
  - template: run-tests-linux.yml
    parameters:
      python_version: $(python.version)

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Python $(python.version)'
  condition: succeededOrFailed()
