language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "pypy" # too many cache issues
  # - "3.7-dev"  # no need, slows down builds
  # - "pypy3" # TODO: pkg_config issues

# command to install dependencies
install:
  - "pip install --upgrade setuptools"
  - "pip install -e . --upgrade"
  - "pipenv install --dev"

# command to run the dependencies
script:
  - "pipenv run pytest -n 8 tests"

# command to run tests
# jobs:
  # include:
    # - stage: "✨ Flake8 Nit–Picking ✨"
      # python: "3.6"
      # script: "pipenv run flake8"
