language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev"
  # - "pypy"
  # - "pypy3" # TODO: pkg_config issues

# command to install dependencies
install:
  - "pip install -e ."
  - "pipenv install --dev --skip-lock"
# command to run tests
script:
  # flake8 has dropped support for Python 2.6.
  # - if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]]; then pipenv run flake8 --ignore=F821; fi
  - pipenv run pytest tests
