sudo: false
dist: trusty
cache: pip
language: python
python:
  - "3.6"
  - "2.7"
env:
  - TEST_SUITE='dotvenv or check or unused or requirements'
  - TEST_SUITE='complex'
  - TEST_SUITE='markers or run or project or utils'

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -e . --upgrade --upgrade-strategy=only-if-needed"
  - "pipenv install --dev"

# command to run the dependencies
script:
  - "pipenv run bash ./run-tests.sh"

jobs:
  include:
    - stage: integration
      env: TEST_SUITE='cli'
    - stage: takes-forever
      env: TEST_SUITE='install'

stages:
  - integration
  - test
  - name: takes-forever
    if: branch = master
