language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev"
  # - "pypy"
  # - "pypy3" # TODO: pkg_config issues

# command to install dependencies
install:
  - "pip install -e . --upgrade"
  - "pipenv install --dev"

# command to run the dependencies
script:
  - "pipenv run pytest tests"

# command to run tests
jobs:
  include:
    - stage: "✨ Flake8 Nit–Picking ✨"
      python: "3.6"
      script: "pipenv run flake8"
